export enum AssetStatus {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  OVERDUE = 'OVERDUE',
  MAINTENANCE = 'MAINTENANCE',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}

export enum MachineType {
  EXCAVATOR = 'EXCAVATOR',
  DOZER = 'DOZER',
  WHEEL_LOADER = 'WHEEL_LOADER',
  MOTOR_GRADER = 'MOTOR_GRADER',
  SKID_STEER = 'SKID_STEER',
  ARTICULATED_TRUCK = 'ARTICULATED_TRUCK',
  CRANE = 'CRANE',
}

export enum RentalStatus {
  RESERVED = 'RESERVED',
  ACTIVE = 'ACTIVE',
  RETURNED = 'RETURNED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum AlertType {
  OVERDUE_RETURN = 'OVERDUE_RETURN',
  HIGH_IDLE_ANOMALY = 'HIGH_IDLE_ANOMALY',
  UNASSIGNED_USAGE = 'UNASSIGNED_USAGE',
  DIAGNOSTIC_FAULT_CODE = 'DIAGNOSTIC_FAULT_CODE',
  GEOFENCE_BREACH = 'GEOFENCE_BREACH',
  MAINTENANCE_DUE = 'MAINTENANCE_DUE',
}

export enum AlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum AlertStatus {
  ACTIVE = 'ACTIVE',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  FLEET_MANAGER = 'FLEET_MANAGER',
  DISPATCHER = 'DISPATCHER',
  OPERATOR = 'OPERATOR',
  TECHNICIAN = 'TECHNICIAN',
}
