import {
  Asset,
  Rental,
  TelemetryLog,
  Site,
  Operator,
  Alert,
  AssetStatus,
  MachineType,
  RentalStatus,
  AlertType,
  AlertSeverity,
  AlertStatus,
} from '../models/index.ts';

export class DbStore {
  public assets: Map<string, Asset> = new Map();
  public rentals: Map<string, Rental> = new Map();
  public telemetryLogs: TelemetryLog[] = [];
  public sites: Map<string, Site> = new Map();
  public operators: Map<string, Operator> = new Map();
  public alerts: Map<string, Alert> = new Map();

  constructor() {
    this.seedInitialData();
  }

  public seedInitialData() {
    // 1. Sites
    const initialSites: Site[] = [
      {
        id: 'S001',
        name: 'Granite Hill Mining & Quarry',
        customer: 'Central Texas Aggregates',
        latitude: 30.3842,
        longitude: -97.7289,
        geofenceRadiusMeters: 450,
        requiredMachineTypes: [MachineType.EXCAVATOR, MachineType.MOTOR_GRADER],
        activeMachinesCount: 2,
        projectedDurationDays: 120,
      },
      {
        id: 'S002',
        name: 'South Austin Logistics Park',
        customer: 'Prologis Development',
        latitude: 30.2012,
        longitude: -97.7712,
        geofenceRadiusMeters: 600,
        requiredMachineTypes: [MachineType.EXCAVATOR, MachineType.WHEEL_LOADER],
        activeMachinesCount: 2,
        projectedDurationDays: 45,
      },
      {
        id: 'S003',
        name: 'Metro Expressway Extension',
        customer: 'Austin InfraBuild Consortium',
        latitude: 30.3122,
        longitude: -97.6841,
        geofenceRadiusMeters: 850,
        requiredMachineTypes: [MachineType.EXCAVATOR, MachineType.DOZER],
        activeMachinesCount: 2,
        projectedDurationDays: 90,
      },
      {
        id: 'S004',
        name: 'Riverbend Commercial Core',
        customer: 'Riverside Urban LLC',
        latitude: 30.2522,
        longitude: -97.7121,
        geofenceRadiusMeters: 300,
        requiredMachineTypes: [MachineType.EXCAVATOR, MachineType.SKID_STEER],
        activeMachinesCount: 1,
        projectedDurationDays: 60,
      },
      {
        id: 'S005',
        name: 'Highland Ridge Residential',
        customer: 'Lennar Homes Central',
        latitude: 30.412,
        longitude: -97.654,
        geofenceRadiusMeters: 500,
        requiredMachineTypes: [MachineType.SKID_STEER, MachineType.WHEEL_LOADER],
        activeMachinesCount: 0,
        projectedDurationDays: 30,
      },
      {
        id: 'S006',
        name: 'North Ridge Quarry & Earthworks',
        customer: 'Texas Heavy Materials',
        latitude: 30.441,
        longitude: -97.801,
        geofenceRadiusMeters: 700,
        requiredMachineTypes: [MachineType.EXCAVATOR, MachineType.DOZER, MachineType.ARTICULATED_TRUCK],
        activeMachinesCount: 2,
        projectedDurationDays: 180,
      },
    ];
    initialSites.forEach((s) => this.sites.set(s.id, s));

    // 2. Operators
    const initialOperators: Operator[] = [
      {
        id: 'OP-101',
        name: 'Marcus Ramirez',
        certifications: [MachineType.EXCAVATOR, MachineType.DOZER],
        experienceYears: 8,
        assignedAssetId: 'EQX1001',
        assignedSiteId: 'S003',
        status: 'ACTIVE',
      },
      {
        id: 'OP-102',
        name: 'Sarah Jenkins',
        certifications: [MachineType.EXCAVATOR, MachineType.WHEEL_LOADER],
        experienceYears: 12,
        assignedAssetId: 'EQX1003',
        assignedSiteId: 'S002',
        status: 'ACTIVE',
      },
      {
        id: 'OP-103',
        name: 'David Vance',
        certifications: [MachineType.EXCAVATOR],
        experienceYears: 4,
        assignedAssetId: 'EQX1004',
        assignedSiteId: 'S004',
        status: 'ACTIVE',
      },
      {
        id: 'OP-104',
        name: 'Elena Rostova',
        certifications: [MachineType.MOTOR_GRADER, MachineType.DOZER],
        experienceYears: 15,
        assignedAssetId: 'EQX1006',
        assignedSiteId: 'S001',
        status: 'ACTIVE',
      },
      {
        id: 'OP-105',
        name: 'Tyler Johnson',
        certifications: [MachineType.SKID_STEER, MachineType.EXCAVATOR],
        experienceYears: 6,
        assignedAssetId: 'CAT-SS-299-05',
        assignedSiteId: 'S002',
        status: 'ACTIVE',
      },
    ];
    initialOperators.forEach((o) => this.operators.set(o.id, o));

    // 3. Assets
    const initialAssets: Asset[] = [
      {
        id: 'EQX1001',
        model: 'Cat 320 Hydraulic Excavator',
        machineType: MachineType.EXCAVATOR,
        serialNumber: 'CAT00320TX88101',
        status: AssetStatus.RENTED,
        healthIndex: 82,
        totalEngineHours: 1420.5,
        totalIdleHours: 610.2,
        fuelLevelPercent: 68,
        dayRateUsd: 750,
        currentSiteId: 'S003',
        assignedOperatorId: 'OP-101',
        activeRentalId: 'RNT-2026-0901',
        qrCode: 'QR-EQX1001',
        telemetryLive: {
          lat: 30.3122,
          lng: -97.6841,
          engineRpm: 1200,
          fuelPercent: 68,
          hydraulicPressurePsi: 4100,
          batteryVoltage: 24.8,
          coolantTempC: 84,
          engineHours: 1420.5,
          idleHours: 610.2,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-10',
        nextServiceHours: 1500,
      },
      {
        id: 'EQX1002',
        model: 'Cat RT-60 Rough Terrain Crane',
        machineType: MachineType.CRANE,
        serialNumber: 'CAT00RTC60TX002',
        status: AssetStatus.AVAILABLE,
        healthIndex: 94,
        totalEngineHours: 840.0,
        totalIdleHours: 210.0,
        fuelLevelPercent: 95,
        dayRateUsd: 1450,
        currentSiteId: null,
        assignedOperatorId: null,
        activeRentalId: null,
        qrCode: 'QR-EQX1002',
        telemetryLive: {
          lat: 30.2672,
          lng: -97.7431,
          engineRpm: 0,
          fuelPercent: 95,
          hydraulicPressurePsi: 0,
          batteryVoltage: 25.4,
          coolantTempC: 22,
          engineHours: 840.0,
          idleHours: 210.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-15',
        nextServiceHours: 1000,
      },
      {
        id: 'EQX1003',
        model: 'Cat 950M Medium Wheel Loader',
        machineType: MachineType.WHEEL_LOADER,
        serialNumber: 'CAT00950TX99303',
        status: AssetStatus.RENTED,
        healthIndex: 91,
        totalEngineHours: 2310.0,
        totalIdleHours: 420.0,
        fuelLevelPercent: 82,
        dayRateUsd: 820,
        currentSiteId: 'S002',
        assignedOperatorId: 'OP-102',
        activeRentalId: 'RNT-2026-0902',
        qrCode: 'QR-EQX1003',
        telemetryLive: {
          lat: 30.2012,
          lng: -97.7712,
          engineRpm: 1650,
          fuelPercent: 82,
          hydraulicPressurePsi: 3850,
          batteryVoltage: 24.9,
          coolantTempC: 86,
          engineHours: 2310.0,
          idleHours: 420.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-07-28',
        nextServiceHours: 2500,
      },
      {
        id: 'EQX1004',
        model: 'Cat 349 Large Excavator',
        machineType: MachineType.EXCAVATOR,
        serialNumber: 'CAT00349TX77404',
        status: AssetStatus.RENTED,
        healthIndex: 78,
        totalEngineHours: 3620.0,
        totalIdleHours: 1480.0,
        fuelLevelPercent: 44,
        dayRateUsd: 1250,
        currentSiteId: 'S004',
        assignedOperatorId: 'OP-103',
        activeRentalId: 'RNT-2026-0903',
        qrCode: 'QR-EQX1004',
        telemetryLive: {
          lat: 30.2522,
          lng: -97.7121,
          engineRpm: 900,
          fuelPercent: 44,
          hydraulicPressurePsi: 3950,
          batteryVoltage: 24.3,
          coolantTempC: 88,
          engineHours: 3620.0,
          idleHours: 1480.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-01',
        nextServiceHours: 3750,
      },
      {
        id: 'EQX1005',
        model: 'Cat D8T Heavy Track Bulldozer',
        machineType: MachineType.DOZER,
        serialNumber: 'CAT00D8TTX55505',
        status: AssetStatus.AVAILABLE,
        healthIndex: 96,
        totalEngineHours: 1150.0,
        totalIdleHours: 180.0,
        fuelLevelPercent: 100,
        dayRateUsd: 1350,
        currentSiteId: null,
        assignedOperatorId: null,
        activeRentalId: null,
        qrCode: 'QR-EQX1005',
        telemetryLive: {
          lat: 30.2672,
          lng: -97.7431,
          engineRpm: 0,
          fuelPercent: 100,
          hydraulicPressurePsi: 0,
          batteryVoltage: 25.5,
          coolantTempC: 21,
          engineHours: 1150.0,
          idleHours: 180.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-20',
        nextServiceHours: 1250,
      },
      {
        id: 'EQX1006',
        model: 'Cat 16M3 Motor Grader',
        machineType: MachineType.MOTOR_GRADER,
        serialNumber: 'CAT0016MTX33606',
        status: AssetStatus.RENTED,
        healthIndex: 88,
        totalEngineHours: 1890.0,
        totalIdleHours: 490.0,
        fuelLevelPercent: 71,
        dayRateUsd: 1100,
        currentSiteId: 'S001',
        assignedOperatorId: 'OP-104',
        activeRentalId: 'RNT-2026-0904',
        qrCode: 'QR-EQX1006',
        telemetryLive: {
          lat: 30.3842,
          lng: -97.7289,
          engineRpm: 1800,
          fuelPercent: 71,
          hydraulicPressurePsi: 3600,
          batteryVoltage: 25.0,
          coolantTempC: 85,
          engineHours: 1890.0,
          idleHours: 490.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-07-15',
        nextServiceHours: 2000,
      },
      {
        id: 'EQX1007',
        model: 'Cat 323 Medium Excavator',
        machineType: MachineType.EXCAVATOR,
        serialNumber: 'CAT00323TX22707',
        status: AssetStatus.AVAILABLE,
        healthIndex: 85,
        totalEngineHours: 920.0,
        totalIdleHours: 340.0,
        fuelLevelPercent: 55,
        dayRateUsd: 790,
        currentSiteId: null,
        assignedOperatorId: null,
        activeRentalId: null,
        qrCode: 'QR-EQX1007',
        telemetryLive: {
          lat: 30.2672,
          lng: -97.7431,
          engineRpm: 0,
          fuelPercent: 55,
          hydraulicPressurePsi: 0,
          batteryVoltage: 24.6,
          coolantTempC: 24,
          engineHours: 920.0,
          idleHours: 340.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-05',
        nextServiceHours: 1000,
      },
      {
        id: 'CAT-DZ-D6-02',
        model: 'Cat D6 XE Electric Drive Dozer',
        machineType: MachineType.DOZER,
        serialNumber: 'CAT00D6XETX11002',
        status: AssetStatus.OVERDUE,
        healthIndex: 72,
        totalEngineHours: 2180.0,
        totalIdleHours: 720.0,
        fuelLevelPercent: 32,
        dayRateUsd: 950,
        currentSiteId: 'S003',
        assignedOperatorId: 'OP-101',
        activeRentalId: 'RNT-2026-0815',
        qrCode: 'QR-CAT-D6-02',
        telemetryLive: {
          lat: 30.3122,
          lng: -97.6841,
          engineRpm: 1100,
          fuelPercent: 32,
          hydraulicPressurePsi: 3900,
          batteryVoltage: 24.1,
          coolantTempC: 91,
          engineHours: 2180.0,
          idleHours: 720.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-07-10',
        nextServiceHours: 2250,
      },
      {
        id: 'CAT-SS-299-05',
        model: 'Cat 299D3 Compact Track Loader',
        machineType: MachineType.SKID_STEER,
        serialNumber: 'CAT0299D3TX44005',
        status: AssetStatus.MAINTENANCE,
        healthIndex: 58,
        totalEngineHours: 1540.0,
        totalIdleHours: 380.0,
        fuelLevelPercent: 88,
        dayRateUsd: 480,
        currentSiteId: null,
        assignedOperatorId: null,
        activeRentalId: null,
        qrCode: 'QR-CAT-299-05',
        telemetryLive: {
          lat: 30.2672,
          lng: -97.7431,
          engineRpm: 0,
          fuelPercent: 88,
          hydraulicPressurePsi: 0,
          batteryVoltage: 22.8,
          coolantTempC: 20,
          engineHours: 1540.0,
          idleHours: 380.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-25',
        nextServiceHours: 1550,
      },
      {
        id: 'CAT-AT-745-01',
        model: 'Cat 745 Articulated Dump Truck',
        machineType: MachineType.ARTICULATED_TRUCK,
        serialNumber: 'CAT00745TX66001',
        status: AssetStatus.RENTED,
        healthIndex: 90,
        totalEngineHours: 2850.0,
        totalIdleHours: 510.0,
        fuelLevelPercent: 78,
        dayRateUsd: 1600,
        currentSiteId: 'S006',
        assignedOperatorId: 'OP-104',
        activeRentalId: 'RNT-2026-0820',
        qrCode: 'QR-CAT-745-01',
        telemetryLive: {
          lat: 30.441,
          lng: -97.801,
          engineRpm: 1950,
          fuelPercent: 78,
          hydraulicPressurePsi: 3750,
          batteryVoltage: 25.1,
          coolantTempC: 87,
          engineHours: 2850.0,
          idleHours: 510.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-01',
        nextServiceHours: 3000,
      },
      {
        id: 'CAT-EX-336-09',
        model: 'Cat 336 Next Gen Excavator',
        machineType: MachineType.EXCAVATOR,
        serialNumber: 'CAT00336TX88009',
        status: AssetStatus.RENTED,
        healthIndex: 92,
        totalEngineHours: 1100.0,
        totalIdleHours: 190.0,
        fuelLevelPercent: 85,
        dayRateUsd: 890,
        currentSiteId: 'S006',
        assignedOperatorId: 'OP-103',
        activeRentalId: 'RNT-2026-0822',
        qrCode: 'QR-CAT-336-09',
        telemetryLive: {
          lat: 30.441,
          lng: -97.801,
          engineRpm: 1720,
          fuelPercent: 85,
          hydraulicPressurePsi: 4000,
          batteryVoltage: 25.2,
          coolantTempC: 84,
          engineHours: 1100.0,
          idleHours: 190.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-12',
        nextServiceHours: 1250,
      },
      {
        id: 'CAT-WL-966-03',
        model: 'Cat 966 XE Wheel Loader',
        machineType: MachineType.WHEEL_LOADER,
        serialNumber: 'CAT00966TX33003',
        status: AssetStatus.IN_TRANSIT,
        healthIndex: 95,
        totalEngineHours: 620.0,
        totalIdleHours: 95.0,
        fuelLevelPercent: 92,
        dayRateUsd: 880,
        currentSiteId: null,
        assignedOperatorId: null,
        activeRentalId: null,
        qrCode: 'QR-CAT-966-03',
        telemetryLive: {
          lat: 30.290,
          lng: -97.710,
          engineRpm: 0,
          fuelPercent: 92,
          hydraulicPressurePsi: 0,
          batteryVoltage: 25.3,
          coolantTempC: 25,
          engineHours: 620.0,
          idleHours: 95.0,
          lastUpdated: new Date().toISOString(),
        },
        lastServiceDate: '2026-08-18',
        nextServiceHours: 750,
      },
    ];
    initialAssets.forEach((a) => this.assets.set(a.id, a));

    // 4. Rentals
    const initialRentals: Rental[] = [
      {
        id: 'RNT-2026-0901',
        assetId: 'EQX1001',
        siteId: 'S003',
        customerName: 'Austin InfraBuild Consortium',
        operatorId: 'OP-101',
        status: RentalStatus.ACTIVE,
        checkOutDate: '2026-08-27',
        expectedCheckInDate: '2026-09-05',
        initialEngineHours: 1412.0,
        initialFuelPercent: 95,
        dayRateUsd: 750,
        contractNumber: 'CAT-CON-2026-901',
      },
      {
        id: 'RNT-2026-0902',
        assetId: 'EQX1003',
        siteId: 'S002',
        customerName: 'Prologis Development',
        operatorId: 'OP-102',
        status: RentalStatus.ACTIVE,
        checkOutDate: '2026-08-20',
        expectedCheckInDate: '2026-09-10',
        initialEngineHours: 2250.0,
        initialFuelPercent: 100,
        dayRateUsd: 820,
        contractNumber: 'CAT-CON-2026-902',
      },
      {
        id: 'RNT-2026-0903',
        assetId: 'EQX1004',
        siteId: 'S004',
        customerName: 'Riverside Urban LLC',
        operatorId: 'OP-103',
        status: RentalStatus.ACTIVE,
        checkOutDate: '2026-08-28',
        expectedCheckInDate: '2026-09-04',
        initialEngineHours: 3612.0,
        initialFuelPercent: 90,
        dayRateUsd: 1250,
        contractNumber: 'CAT-CON-2026-903',
      },
      {
        id: 'RNT-2026-0904',
        assetId: 'EQX1006',
        siteId: 'S001',
        customerName: 'Central Texas Aggregates',
        operatorId: 'OP-104',
        status: RentalStatus.ACTIVE,
        checkOutDate: '2026-08-30',
        expectedCheckInDate: '2026-09-08',
        initialEngineHours: 1870.0,
        initialFuelPercent: 100,
        dayRateUsd: 1100,
        contractNumber: 'CAT-CON-2026-904',
      },
      {
        id: 'RNT-2026-0815',
        assetId: 'CAT-DZ-D6-02',
        siteId: 'S003',
        customerName: 'Austin InfraBuild Consortium',
        operatorId: 'OP-101',
        status: RentalStatus.OVERDUE,
        checkOutDate: '2026-08-15',
        expectedCheckInDate: '2026-08-30', // Overdue!
        initialEngineHours: 2150.0,
        initialFuelPercent: 95,
        dayRateUsd: 950,
        overdueDailyPenaltyUsd: 350,
        contractNumber: 'CAT-CON-2026-815',
      },
      {
        id: 'RNT-2026-0820',
        assetId: 'CAT-AT-745-01',
        siteId: 'S006',
        customerName: 'Texas Heavy Materials',
        operatorId: 'OP-104',
        status: RentalStatus.ACTIVE,
        checkOutDate: '2026-08-20',
        expectedCheckInDate: '2026-09-20',
        initialEngineHours: 2750.0,
        initialFuelPercent: 100,
        dayRateUsd: 1600,
        contractNumber: 'CAT-CON-2026-820',
      },
      {
        id: 'RNT-2026-0822',
        assetId: 'CAT-EX-336-09',
        siteId: 'S006',
        customerName: 'Texas Heavy Materials',
        operatorId: 'OP-103',
        status: RentalStatus.ACTIVE,
        checkOutDate: '2026-08-22',
        expectedCheckInDate: '2026-09-15',
        initialEngineHours: 1020.0,
        initialFuelPercent: 95,
        dayRateUsd: 890,
        contractNumber: 'CAT-CON-2026-822',
      },
    ];
    initialRentals.forEach((r) => this.rentals.set(r.id, r));

    // 5. Benchmark Telemetry Logs (Problem Statement Dataset)
    this.telemetryLogs = [
      {
        id: 'LOG-001',
        assetId: 'EQX1001',
        daysDuration: 5,
        engineHoursDay: 1.5,
        idleHoursDay: 10.0,
        siteId: 'S003',
        operatorId: 'OP-101',
        fuelConsumedLiters: 220,
        diagnosticCodes: [],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: true,
      },
      {
        id: 'LOG-002',
        assetId: 'EQX1002',
        daysDuration: 1,
        engineHoursDay: 0.0,
        idleHoursDay: 11.0,
        siteId: null,
        operatorId: null,
        fuelConsumedLiters: 110,
        diagnosticCodes: [],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: true,
      },
      {
        id: 'LOG-003',
        assetId: 'EQX1003',
        daysDuration: 10,
        engineHoursDay: 6.0,
        idleHoursDay: 0.7,
        siteId: 'S002',
        operatorId: 'OP-102',
        fuelConsumedLiters: 380,
        diagnosticCodes: [],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: false,
      },
      {
        id: 'LOG-004',
        assetId: 'EQX1004',
        daysDuration: 3,
        engineHoursDay: 2.0,
        idleHoursDay: 8.5,
        siteId: 'S004',
        operatorId: 'OP-103',
        fuelConsumedLiters: 190,
        diagnosticCodes: [],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: true,
      },
      {
        id: 'LOG-005',
        assetId: 'EQX1005',
        daysDuration: 2,
        engineHoursDay: 0.0,
        idleHoursDay: 0.0,
        siteId: null,
        operatorId: null,
        fuelConsumedLiters: 0,
        diagnosticCodes: [],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: false,
      },
      {
        id: 'LOG-006',
        assetId: 'EQX1006',
        daysDuration: 1,
        engineHoursDay: 12.0,
        idleHoursDay: 4.5,
        siteId: 'S001',
        operatorId: 'OP-104',
        fuelConsumedLiters: 160,
        diagnosticCodes: [],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: false,
      },
      {
        id: 'LOG-007',
        assetId: 'EQX1007',
        daysDuration: 1,
        engineHoursDay: 0.0,
        idleHoursDay: 12.0,
        siteId: null,
        operatorId: null,
        fuelConsumedLiters: 120,
        diagnosticCodes: [],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: true,
      },
      {
        id: 'LOG-008',
        assetId: 'CAT-DZ-D6-02',
        daysDuration: 1,
        engineHoursDay: 3.5,
        idleHoursDay: 5.5,
        siteId: 'S003',
        operatorId: 'OP-101',
        fuelConsumedLiters: 85,
        diagnosticCodes: ['SPN 3509 FMI 4'],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: true,
      },
      {
        id: 'LOG-009',
        assetId: 'CAT-SS-299-05',
        daysDuration: 1,
        engineHoursDay: 0.0,
        idleHoursDay: 0.0,
        siteId: null,
        operatorId: null,
        fuelConsumedLiters: 0,
        diagnosticCodes: ['SPN 3509 FMI 4 - Sensor Supply 1 Voltage Low'],
        timestamp: '2026-08-31T18:00:00Z',
        anomalyDetected: true,
      },
    ];

    // 6. Initial Operational Alerts
    const initialAlerts: Alert[] = [
      {
        id: 'ALT-OVD-CAT-DZ-D6-02',
        type: AlertType.OVERDUE_RETURN,
        severity: AlertSeverity.CRITICAL,
        assetId: 'CAT-DZ-D6-02',
        assetModel: 'Cat D6 XE Electric Drive Dozer',
        siteId: 'S003',
        contractNumber: 'CAT-CON-2026-815',
        customerName: 'Austin InfraBuild Consortium',
        message: 'Contract overdue by 2 days. Machine is active on site S003 without authorized extension.',
        status: AlertStatus.ACTIVE,
        createdAt: '2026-08-31T06:00:00Z',
      },
      {
        id: 'ALT-IDLE-EQX1001',
        type: AlertType.HIGH_IDLE_ANOMALY,
        severity: AlertSeverity.WARNING,
        assetId: 'EQX1001',
        assetModel: 'Cat 320 Hydraulic Excavator',
        siteId: 'S003',
        message: 'High Idle Anomaly: 10.0h idle/day vs 1.5h runtime (87% idle ratio). Estimated waste: $1,850.',
        status: AlertStatus.ACTIVE,
        createdAt: '2026-08-31T12:00:00Z',
      },
      {
        id: 'ALT-DTC-CAT-SS-299-05',
        type: AlertType.DIAGNOSTIC_FAULT_CODE,
        severity: AlertSeverity.CRITICAL,
        assetId: 'CAT-SS-299-05',
        assetModel: 'Cat 299D3 Compact Track Loader',
        siteId: null,
        message: 'Active Diagnostic Code: SPN 3509 FMI 4 (Sensor Supply 1 Voltage Low). ECM battery at 22.8V.',
        status: AlertStatus.ACTIVE,
        createdAt: '2026-08-31T08:30:00Z',
      },
      {
        id: 'ALT-UNASSIGNED-EQX1002',
        type: AlertType.UNASSIGNED_USAGE,
        severity: AlertSeverity.WARNING,
        assetId: 'EQX1002',
        assetModel: 'Cat RT-60 Rough Terrain Crane',
        siteId: null,
        message: 'Unassigned machine running: 11.0h idle logged with no customer contract attached.',
        status: AlertStatus.ACTIVE,
        createdAt: '2026-08-31T14:15:00Z',
      },
    ];
    initialAlerts.forEach((a) => this.alerts.set(a.id, a));
  }
}

export const dbStore = new DbStore();
